### ISSUE TITLE
restore "promise-calling" to be a linkable defined term? 

### ISSUE THREAD

**Issue by equalsJeffH** [w3ctag/promises-guide#64]
It'd be helpful if "promise-calling" would be made (restored as?) a `<dfn>` so other specs can auto-link to it, e.g., as https://www.w3.org/TR/credential-management-1/ does (the link now does not resolve correctly (it used to IIRC)). thx.

**Comment by marcoscaceres** [comment]
@equalsJeffH, the promises guide merged into the WebIDL spec. Not sure if what you need is there (doesn't seem "promise calling" is there)... but likely what you want is already exported.

**Comment by annevk** [comment]
@equalsJeffH see links from #27. This is intentional and you'll need to refactor. Unfortunately we don't have tooling yet whereby we can find all downstream dependencies and notify them of a change.

**Comment by domenic** [comment]
Indeed. Promise calling is no longer needed; as long as you use Web IDL promise-returning callback types, you get that automatically by using the usual "invoke" hook.

Or in other words, per https://www.w3.org/2001/tag/doc/promises-guide#should-promise-call ,

> In Web IDL-using specifications, this is automatically taken care of if you declare the developer function as a callback function and then invoke it.

Hope this helps. I'll close the issue since we won't be adding a separate promise-calling operation back, but feel free to ask here or elsewhere if you need help with using Web IDL callback functions.

**Comment by equalsJeffH** [comment]
Thx @domenic -- I do have a question: what we are presently "promise-calling" in the [credential-management (credman) spec](https://w3c.github.io/webappsec-credential-management/) is an _algorithm_ returned by webauthn.  

You can find this returned webauthn alg by searching the [webauthn editors' draft spec](https://w3c.github.io/webauthn/) for "Let constructCredentialAlg be".  Where it is invoked from credman can be found by searching the [credman editors' draft](https://w3c.github.io/webappsec-credential-management/) for "promise-calling". 

Ought we formally declare that alg in webauthn as ([this flavor](https://heycam.github.io/webidl/#idl-callback-function) of) a [callback function](https://heycam.github.io/webidl/#Function)? And then I'm wondering whether it will more or less work automagically if we [invoke](https://heycam.github.io/webidl/#invoke-a-callback-function) it from credman.  Tho, the invoke alg assumes the callback function is written in script?  Is what we're trying to do here similar to to what Issue 6 in [WebIDL S 2.10. Callback functions](https://heycam.github.io/webidl/#idl-callback-functions) is talking about where it says:
> ...use callback function types for platform object provided functions... 

...?

**Comment by domenic** [comment]
Ah, hmm, that's a bit strange. Promise-calling only ever worked on JS functions.

Since I assume the algorithms in question are from specifications, not provided by authors, it seems like promise-calling is less necessary: you can just update the specifications to always return promises. That would be my advice.

**Comment by equalsJeffH** [comment]
ok, thx, I'll give that a shot :)
